version: "3"

services:
    db:
      platform: linux/x86_64
      image: mysql:5.7
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        
      
      ports:
        - "3307:3306"
      command: --disable-partition-engine-check
      volumes: 
        - .data/db:/var/lib/mysql

    
    web:
      build: 
        context : .
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        - db
     
      

