# Generated by Django 3.2.6 on 2021-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('unvan', models.CharField(max_length=250)),
                ('birth', models.CharField(max_length=250)),
                ('death', models.CharField(max_length=250)),
                ('life', models.CharField(max_length=500)),
            ],
        ),
    ]
