# Generated by Django 3.2.6 on 2021-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=100)),
                ('birth', models.TextField(max_length=100)),
                ('death', models.TextField(max_length=100)),
                ('life', models.TextField()),
            ],
        ),
    ]
