# Generated by Django 3.2.6 on 2021-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='death',
            field=models.CharField(max_length=100),
        ),
    ]
