# Generated by Django 3.2.6 on 2021-08-17 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_auto_20210817_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('page_number', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('book_summary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.authormodel')),
                ('typeofbook', models.ManyToManyField(to='book.TypeOfBookModel')),
            ],
        ),
    ]
